# Generated by Django 4.0.6 on 2022-08-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk', 'book_name'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
